### ISSUE TITLE
Silex framework is deprecated/EOL'd; example is out of date

### ISSUE THREAD

**Issue by pgnd** [gentics/mesh-website-blog#3]
fyi,

silex has been deprecated, and was EOL'd June 2018

cref: https://symfony.com/blog/the-end-of-silex

ime, highlighting it on the gentics blog causes more client problems than help.

might consider archiving, if not removing, it.  ideally, replacing with an up-to-date Symfony 4.2 example, if a similar audience is still the target.

**Comment by Jotschi** [comment]
@pgnd Thanks for the feedback. I'll add a note to the blogpost and example.

**Comment by Jotschi** [comment]
Example has been archived and blogpost updated.
